### ISSUE TITLE
Color Format in the README

### ISSUE THREAD

**Issue by pauladam94** [jonasgeiler/lua-fenster#6]
I don't understand what is the color format ?
Because it is just represented as number 

255 seems to be blue
and 0 is black ?

**Comment by pauladam94** [comment]
Ok I figured it out.

```lua
local function rgb(r, g, b)
	return r * 256 * 256 + g * 256 + b
end
```

**Comment by jonasgeiler** [comment]
There is a utility called `fenster.rgb()` which you can use to convert from and to RGB:
```lua
-- RGB to 24-bit color
fenster.rgb(255, 0, 0) -- returns 0xff0000

-- 24-bit color to RGB
fenster.rgb(0xff0000) -- returns 255, 0, 0
```

**Comment by jonasgeiler** [comment]
Similar to #8 I will turn this into a discussion as well in case someone has a similar question in the future.
